### ISSUE TITLE
Bpel-g is not running with Jboss eap 6.2

### ISSUE THREAD

**Issue by DiptiPrakash** [massfords/bpel-g#82]
Hello ,
  I am trying to run bpel-g using JBoss eap 6.2 But it is not working .
But in tomcat i am able to run. But my requirement is , i have to run with JBoss eap 6.2.

I am getting below error . Please guide me how to resolve this issue.

12:00:37,704 INFO  [ActiveBPEL] (ServerService Thread Pool -- 64) Loaded config file from D:\JBoss\jboss-eap-6.2\standalone\tmp\bpr\aeEngineConfig.xml
12:00:37,766 SEVERE [AeException] (ServerService Thread Pool -- 64) org.activebpel.rt.AeException: java.lang.NoClassDefFoundError: net/sf/saxon/variables/VariableResolver
        at org.activebpel.rt.bpel.expr.AeExpressionLanguageClassInfo.initFromString(AeExpressionLanguageClassInfo.java:125)
        at org.activebpel.rt.bpel.expr.AeExpressionLanguageClassInfo.<init>(AeExpressionLanguageClassInfo.java:92)
        at org.activebpel.rt.bpel.expr.AeExpressionLanguageInfo.createClassInfo(AeExpressionLanguageInfo.java:82)
        at org.activebpel.rt.bpel.expr.AeExpressionLanguageInfo.<init>(AeExpressionLanguageInfo.java:68)
        at org.activebpel.rt.bpel.expr.AeAbstractBpelExpressionLanguageFactory.createLanguageInfo(AeAbstractBpelExpressionLanguageFactory.java:217)
        at org.activebpel.rt.bpel.expr.AeAbstractBpelExpressionLanguageFactory.createLanguageInfo(AeAbstractBpelExpressionLanguageFactory.java:200)
        at org.activebpel.rt.bpel.expr.AeAbstractBpelExpressionLanguageFactory.addLanguage(AeAbstractBpelExpressionLanguageFactory.java:182)
        at org.activebpel.rt.bpel.expr.AeAbstractBpelExpressionLanguageFactory.addLanguages(AeAbstractBpelExpressionLanguageFactory.java:146)
        at org.activebpel.rt.bpel.expr.AeAbstractBpelExpressionLanguageFactory.<init>(AeAbstractBpelExpressionLanguageFactory.java:90)
        at org.activebpel.rt.bpel.expr.AeWSBPELExpressionLanguageFactory.<init>(AeWSBPELExpressionLanguageFactory.java:70)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.activebpel.rt.bpel.AeExpressionLanguageFactory.createFactory(AeExpressionLanguageFactory.java:269)
        at org.activebpel.rt.bpel.AeExpressionLanguageFactory.addFactory(AeExpressionLanguageFactory.java:244)
        at org.activebpel.rt.bpel.AeExpressionLanguageFactory.addFactories(AeExpressionLanguageFactory.java:219)
        at org.activebpel.rt.bpel.AeExpressionLanguageFactory.<init>(AeExpressionLanguageFactory.java:103)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:235)
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:148)
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:130)
        at org.activebpel.rt.bpel.config.AeDefaultEngineConfiguration.createConfigSpecificClass(AeDefaultEngineConfiguration.java:950)
        at org.activebpel.rt.bpel.config.AeDefaultEngineConfiguration.createExpressionLanguageFactory(AeDefaultEngineConfiguration.java:199)
        at org.activebpel.rt.bpel.config.AeDefaultEngineConfiguration.loadConfig(AeDefaultEngineConfiguration.java:366)
        at org.activebpel.rt.bpel.server.engine.AeEngineLifecycleWrapper.loadEngineConfig(AeEngineLifecycleWrapper.java:96)
        at org.activebpel.rt.bpel.server.engine.AeEngineLifecycleWrapper.init(AeEngineLifecycleWrapper.java:73)
        at org.activebpel.rt.axis.bpel.web.AeProcessEngineServlet.init(AeProcessEngineServlet.java:133)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1194)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1100)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3591)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3798)
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156)
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60)
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NoClassDefFoundError: net/sf/saxon/variables/VariableResolver
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
        at java.lang.Class.getConstructor0(Class.java:2803)
        at java.lang.Class.getConstructor(Class.java:1718)
        at org.activebpel.rt.bpel.expr.AeExpressionLanguageClassInfo.initFromString(AeExpressionLanguageClassInfo.java:120)
        ... 43 more
Caused by: java.lang.ClassNotFoundException: net.sf.saxon.variables.VariableResolver from [Module "deployment.CIF-Framework.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
        ... 48 more

12:00:38,125 SEVERE [AeException] (ServerService Thread Pool -- 64) Error instantiating org.activebpel.rt.bpel.server.deploy.AeMasterPolicyMapper.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:235)
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:148)
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:130)
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.createConfigSpecificClass(AeEngineFactory.java:799)
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.initializePolicyMapper(AeEngineFactory.java:721)
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.preInit(AeEngineFactory.java:211)
        at org.activebpel.rt.bpel.server.engine.AeEngineLifecycleWrapper.init(AeEngineLifecycleWrapper.java:73)
        at org.activebpel.rt.axis.bpel.web.AeProcessEngineServlet.init(AeProcessEngineServlet.java:133)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1194)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1100)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3591)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3798)
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156)
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60)
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: org.activebpel.rt.AeException: Exception mapping policy assertions for:WSIO
        at org.activebpel.rt.bpel.server.deploy.AeMasterPolicyMapper.init(AeMasterPolicyMapper.java:84)
        at org.activebpel.rt.bpel.server.deploy.AeMasterPolicyMapper.<init>(AeMasterPolicyMapper.java:57)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: org.activebpel.rt.bpel.server.deploy.AeWsioPolicyMapper from [Module "deployment.CIF-Framework.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at org.activebpel.rt.bpel.server.deploy.AeMasterPolicyMapper.init(AeMasterPolicyMapper.java:76)
        ... 26 more

12:00:38,344 SEVERE [ActiveBPEL] (ServerService Thread Pool -- 64) Unable to start ActiveBPEL: org.activebpel.rt.AeException: Error instantiating org.activebpel.rt.bpel.server.deploy.AeMasterPolicyMapper.
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:244) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:148) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:130) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.createConfigSpecificClass(AeEngineFactory.java:799) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.initializePolicyMapper(AeEngineFactory.java:721) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.preInit(AeEngineFactory.java:211) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineLifecycleWrapper.init(AeEngineLifecycleWrapper.java:73) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.axis.bpel.web.AeProcessEngineServlet.init(AeProcessEngineServlet.java:133) [aeEngine-1.0.jar:4.1.0]
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1194) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1100) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3591) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3798) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)

12:00:38,531 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/CIF-Framework]] (ServerService Thread Pool -- 64) JBWEB000289: Servlet AeProcessEngineServlet threw load() exception: org.activebpel.rt.AeException: Error instantiating org.activebpel.rt.bpel.serve
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:244) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:148) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.config.AeConfigurationUtil.createConfigSpecificClass(AeConfigurationUtil.java:130) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.createConfigSpecificClass(AeEngineFactory.java:799) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.initializePolicyMapper(AeEngineFactory.java:721) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineFactory.preInit(AeEngineFactory.java:211) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.bpel.server.engine.AeEngineLifecycleWrapper.init(AeEngineLifecycleWrapper.java:73) [aeEngine-1.0.jar:4.1.0]
        at org.activebpel.rt.axis.bpel.web.AeProcessEngineServlet.init(AeProcessEngineServlet.java:133) [aeEngine-1.0.jar:4.1.0]
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1194) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1100) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3591) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3798) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)

12:00:38,671 INFO  [stdout] (ServerService Thread Pool -- 64) 5035 [ServerService Thread Pool -- 64] ERROR org.apache.axis.configuration.EngineConfigurationFactoryServlet  - Unable to find config file.  Creating new servlet engine config file: /WEB-INF/server-config.wsdd
12:00:38,765 INFO  [org.jboss.as.server] (Controller Boot Thread) JBAS018559: Deployed "CIF-Framework.war" (runtime-name : "CIF-Framework.war")
12:00:38,765 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 24) JBAS018559: Deployed "bpel-g-5.3.war" (runtime-name : "bpel-g-5.3.war")
12:00:38,765 INFO  [org.jboss.as.controller] (Controller Boot Thread) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."bpel-g-5.3.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."bpel-g-5.3.war".INSTALL: JBAS018733: Failed to process phase INSTALL of deployment "bpel-g-5.3.war"

Thanks
DiptiPrakash

**Comment by massfords** [comment]
java.lang.NoClassDefFoundError: net/sf/saxon/variables/VariableResolver

bpel-g (and ActiveBPEL that it's based on) uses an exotic version of Saxon that must be on the classpath. It looks to me like it's missing. Maybe the container it's running in has a conflicting version of Saxon on the classpath? There should be a way of forcing the app classloader to load ahead of the container. Also, I think there's an EAR packaging for bpel-g that may be better suited for you.
